---
title: "Time Series Graphics. Practice."
author: "Your Name"
date: '2022-09-21'
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r setup, warning=F, message=F}
library(fpp3)
```

```{r}
global_economy %>% head()
```

```{r}
tourism %>% head()
```

```{r}
## PRISON ----------------------------------------------------------------------

prison <- readr::read_csv("data/prison_population.csv") %>%
  mutate(Quarter = yearquarter(date)) %>%
  select(-date) %>%
  as_tsibble(
    index = Quarter,
    key = c(state, gender, legal, indigenous)
  )
prison %>% head()
```

```{r}
## PBS ----------------------------------------------------------------------

PBS %>%
  filter(ATC2 == "A10") %>%
  select(Month, Concession, Type, Cost) %>%
  summarise(total_cost = sum(Cost)) %>%
  mutate(total_cost = total_cost / 1e6) -> a10
```

```{r}
a10 %>% head()
```

```{r}
a10 %>%
  autoplot(total_cost)
```

```{r}
a10 %>% gg_season(total_cost, labels = "right")
```

```{r}
a10 %>% gg_season(total_cost, labels = "both") +
  labs(
    y = "$ million",
    title = "Seasonal plot: antidiabetic drug sales"
  )
```

```{r}
a10 %>%
  gg_subseries(total_cost) +
  labs(
    y = "$ million",
    title = "Subseries plot: antidiabetic drug sales"
  )
```

```{r}
## ANSETT ----------------------------------------------------------------------
ansett %>%
```

```{r}
ansett %>%
  autoplot(Passengers)
```

```{r}
ansett %>%
  filter(Class == "Economy") %>%
  autoplot(Passengers)
```

```{r}
ansett %>%
  filter(Airports == "MEL-SYD") %>%
  autoplot(Passengers) +
  labs(title = "Melbourne-Sydney traffic")
```

```{r}
## MAX TEMP ------------------------------------------------------------

maxtemp <- vic_elec %>%
  index_by(Day = date(Time)) %>%
  summarise(Temperature = max(Temperature))
maxtemp %>%
  autoplot(Temperature) +
  labs(y = "Max temperature")
```

```{r}
## LOTS OF EXAMPLES -------------------------------------------------------------

aus_production %>%
  filter(year(Quarter) >= 1980) %>%
  autoplot(Electricity) +
  labs(
    y = "GWh",
    title = "Australian electricity production"
  )
```

```{r}
aus_production %>%
  autoplot(Bricks) +
  labs(
    title = "Australian clay brick production",
    y = "million units"
  )
```

```{r}
us_employment %>%
  filter(Title == "Retail Trade", year(Month) >= 1980) %>%
  autoplot(Employed / 1e3) +
  labs(
    title = "Retail employment, USA",
    y = "Million people"
  )
```

```{r}
gafa_stock %>%
  filter(Symbol == "AMZN", year(Date) >= 2018) %>%
  autoplot(Close) +
  labs(
    title = "Amazon closing stock price",
    y = "$US"
  )
```

```{r}
pelt %>%
  autoplot(Lynx) +
  labs(
    title = "Annual Canadian Lynx Trappings",
    y = "Number trapped"
  )
```

```{r}
## BEER -------------------------------------------------------------------------

beer <- aus_production %>%
  select(Quarter, Beer) %>%
  filter(year(Quarter) >= 1992)
beer %>% autoplot(Beer)

beer %>% gg_season(Beer, labels = "right")
beer %>% gg_subseries(Beer)

beer %>% gg_lag(Beer)
beer %>% gg_lag(Beer, geom = "point", lags = 1:16)
beer %>% ACF(Beer, lag_max = 16)
beer %>%
  ACF(Beer, lag_max = 20) %>%
  autoplot()
beer %>%
  ACF(Beer) %>%
  autoplot()
```

```{r}
## ELECTRICITY DEMAND ---------------------------------------------------------

vic_elec
vic_elec %>% autoplot(Demand)
vic_elec %>% gg_season(Demand)
vic_elec %>% gg_season(Demand, period = "week")
vic_elec %>% gg_season(Demand, period = "day")
```

```{r}
## HOLIDAYS --------------------------------------------------------------------

holidays <- tourism %>%
  mutate(
    State = recode(State,
      "Australian Capital Territory" = "ACT",
      "New South Wales" = "NSW",
      "Northern Territory" = "NT",
      "Queensland" = "QLD",
      "South Australia" = "SA",
      "Tasmania" = "TAS",
      "Victoria" = "VIC",
      "Western Australia" = "WA"
    )
  ) %>%
  filter(Purpose == "Holiday") %>%
  group_by(State) %>%
  summarise(Trips = sum(Trips))
```

```{r}
holidays
```

```{r}
holidays %>%
  autoplot(Trips) +
  labs(
    y = "thousands of trips",
    title = "Australian domestic holiday nights"
  )
```

```{r}
holidays %>%
  gg_season(Trips) +
  labs(
    y = "thousands of trips",
    title = "Australian domestic holiday nights"
  )
```

```{r}
holidays %>%
  gg_subseries(Trips) +
  labs(
    y = "thousands of trips",
    title = "Australian domestic holiday nights"
  )
```
# Autocorrelation
```{r}
## RETAIL TRADE ------------------------------------------------------------------

retail <- us_employment %>%
  filter(Title == "Retail Trade", year(Month) >= 1980)
retail %>% autoplot(Employed)
```

```{r}
retail %>%
  ACF(Employed, lag_max = 48) %>%
  autoplot()
```

```{r}
## Google 2015 -------------------------------------------------------------------

google_2015 <- gafa_stock %>%
  filter(Symbol == "GOOG", year(Date) == 2015) %>%
  select(Date, Close)
google_2015
```

```{r}
google_2015 %>% autoplot(Close)
```

```{r}
google_2015 %>% ACF(Close)
```

```{r}
google_2015 %>%
  ACF(Close, lag_max = 100) %>%
  autoplot()
```

```{r}
## WHITE NOISE --------------------------------------------------------------------

set.seed(30)
wn <- tsibble(t = seq(50), y = rnorm(50), index = t)
```

```{r}
wn %>% autoplot(y)
```

```{r}
wn %>% ACF(y, lag_max = 10)
```

```{r}
wn %>%
  ACF(y) %>%
  autoplot()
```

```{r}
## PIGS ---------------------------------------------------------------------------

pigs <- aus_livestock %>%
  filter(
    State == "Victoria", Animal == "Pigs",
    year(Month) >= 2014
  )
```

```{r}
pigs %>% autoplot(Count / 1e3) +
  labs(
    y = "Thousands",
    title = "Number of pigs slaughtered in Victoria"
  )
```

```{r}
pigs %>%
  mutate(diff = difference(Count, lag = 12)) %>%
  autoplot(diff)
```

```{r}
pigs %>%
  ACF(Count, lag_max = 36) %>%
  autoplot()
```

```{r}
## GOOGLE change in closing price ACF ---------------------------------------------

google_2015 %>%
  ACF(Close) %>%
  autoplot()
```

```{r}
google_2015 %>%
  mutate(diff = difference(Close)) %>%
  autoplot(diff)
```

```{r}
google_2015 %>%
  mutate(diff = difference(Close)) %>%
  ACF(diff) %>%
  autoplot()
```

